languages = (
	('none','Plain text'),
	('markup','HTML'),
	('css','CSS'),
	('clike','C-like'),
	('javascript','JavaScript'),
	('abap','ABAP'),
	('actionscript','ActionScript'),
	('ada','Ada'),
	('apacheconf','Apache'),
	('apl','APL'),
	('applescript','AppleScript'),
	('arduino','Arduino'),
	('arff','ARFF'),
	('asciidoc','AsciiDoc'),
	('asm6502','6502 Assembly'),
	('aspnet','ASP.NET (C#)'),
	('autohotkey','AutoHotkey'),
	('autoit','AutoIt'),
	('bash','Bash'),
	('basic','BASIC'),
	('batch','Batch'),
	('bison','Bison'),
	('brainfuck','Brainfuck'),
	('bro','Bro'),
	('c','C'),
	('csharp','C#'),
	('cpp','C++'),
	('coffeescript','CoffeeScript'),
	('clojure','Clojure'),
	('crystal','Crystal'),
	('csp','Content-Security-Policy'),
	('css-extras','CSS Extras'),
	('d','D'),
	('dart','Dart'),
	('diff','Diff'),
	('django','Django/Jinja2'),
	('docker','Docker'),
	('eiffel','Eiffel'),
	('elixir','Elixir'),
	('elm','Elm'),
	('erb','ERB'),
	('erlang','Erlang'),
	('fsharp','F#'),
	('flow','Flow'),
	('fortran','Fortran'),
	('gherkin','Gherkin'),
	('git','Git'),
	('glsl','GLSL'),
	('go','Go'),
	('graphql','GraphQL'),
	('groovy','Groovy'),
	('haml','Haml'),
	('handlebars','Handlebars'),
	('haskell','Haskell'),
	('haxe','Haxe'),
	('http','HTTP'),
	('hpkp','HTTP Public-Key-Pins'),
	('hsts','HTTP Strict-Transport-Security'),
	('ichigojam','IchigoJam'),
	('icon','Icon'),
	('inform7','Inform 7'),
	('ini','Ini'),
	('io','Io'),
	('j','J'),
	('java','Java'),
	('jolie','Jolie'),
	('json','JSON'),
	('julia','Julia'),
	('keyman','Keyman'),
	('kotlin','Kotlin'),
	('latex','LaTeX'),
	('less','Less'),
	('liquid','Liquid'),
	('lisp','Lisp'),
	('livescript','LiveScript'),
	('lolcode','LOLCODE'),
	('lua','Lua'),
	('makefile','Makefile'),
	('markdown','Markdown'),
	('markup-templating','Markup templating'),
	('matlab','MATLAB'),
	('mel','MEL'),
	('mizar','Mizar'),
	('monkey','Monkey'),
	('n4js','N4JS'),
	('nasm','NASM'),
	('nginx','nginx'),
	('nim','Nim'),
	('nix','Nix'),
	('nsis','NSIS'),
	('objectivec','Objective-C'),
	('ocaml','OCaml'),
	('opencl','OpenCL'),
	('oz','Oz'),
	('parigp','PARI/GP'),
	('parser','Parser'),
	('pascal','Pascal'),
	('perl','Perl'),
	('php','PHP'),
	('php-extras','PHP Extras'),
	('plsql','PL/SQL'),
	('powershell','PowerShell'),
	('processing','Processing'),
	('prolog','Prolog'),
	('properties','.properties'),
	('protobuf','Protocol Buffers'),
	('pug','Pug'),
	('puppet','Puppet'),
	('pure','Pure'),
	('python','Python'),
	('q','Q (kdb+ database)'),
	('qore','Qore'),
	('r','R'),
	('jsx','React JSX'),
	('tsx','React TSX'),
	('renpy',"Ren'py"),
	('reason','Reason'),
	('rest','reST (reStructuredText)'),
	('rip','Rip'),
	('roboconf','Roboconf'),
	('ruby','Ruby'),
	('rust','Rust'),
	('sas','SAS'),
	('sass','Sass (Sass)'),
	('scss','Sass (Scss)'),
	('scala','Scala'),
	('scheme','Scheme'),
	('smalltalk','Smalltalk'),
	('smarty','Smarty'),
	('sql','SQL'),
	('stylus','Stylus'),
	('swift','Swift'),
	('tcl','Tcl'),
	('textile','Textile'),
	('twig','Twig'),
	('typescript','TypeScript'),
	('vbnet','VB.Net'),
	('verilog','Verilog'),
	('vhdl','VHDL'),
	('vim','vim'),
	('wiki','Wiki markup'),
	('xeora','Xeora'),
	('xojo','Xojo (REALbasic)'),
	('yaml','YAML'),
)

