# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-14 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('time_updated',)},
        ),
    ]
