# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-11 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180410_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_exposure',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20),
        ),
    ]
